// <auto-generated />
using System;
using Lyke.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lyke.Infrastructure.Data.Migrations
{
    [DbContext(typeof(LykeDbContext))]
    [Migration("20260225123752_AddStatureAndBuild")]
    partial class AddStatureAndBuild
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lyke.Core.Entities.AnalyticsEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Properties")
                        .HasColumnType("jsonb");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AnalyticsEvents_CreatedAt");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AnalyticsEvents_UserId");

                    b.HasIndex("EventType", "CreatedAt")
                        .HasDatabaseName("IX_AnalyticsEvents_EventType_CreatedAt");

                    b.ToTable("AnalyticsEvents");
                });

            modelBuilder.Entity("Lyke.Core.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("IX_AuditLogs_Action");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("IX_AuditLogs_TargetUserId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_AuditLogs_Timestamp");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AuditLogs_UserId");

                    b.HasIndex("TargetUserId", "Timestamp")
                        .HasDatabaseName("IX_AuditLogs_TargetUserId_Timestamp");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Lyke.Core.Entities.BodyProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BodyTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Build")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FitPreference")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("FrameSizeId")
                        .HasColumnType("integer");

                    b.Property<int>("HeightCm")
                        .HasColumnType("integer");

                    b.Property<string>("Stature")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("FrameSizeId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("BodyTypeId", "FrameSizeId", "HeightCm", "WeightKg")
                        .HasDatabaseName("IX_BodyProfiles_BodyType_FrameSize_Height_Weight");

                    b.ToTable("BodyProfiles");
                });

            modelBuilder.Entity("Lyke.Core.Entities.BodyProfileFitPreference", b =>
                {
                    b.Property<Guid>("BodyProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("FitPreference")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("BodyProfileId", "FitPreference");

                    b.ToTable("BodyProfileFitPreferences");
                });

            modelBuilder.Entity("Lyke.Core.Entities.BodyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("BodyTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Balanced bust and hips with defined waist",
                            DisplayOrder = 1,
                            Name = "Hourglass"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Hips wider than shoulders",
                            DisplayOrder = 2,
                            Name = "Pear"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fuller midsection with slimmer legs",
                            DisplayOrder = 3,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Balanced proportions, less waist definition",
                            DisplayOrder = 4,
                            Name = "Rectangle"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Shoulders wider than hips",
                            DisplayOrder = 5,
                            Name = "Inverted Triangle"
                        });
                });

            modelBuilder.Entity("Lyke.Core.Entities.ClickEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttributionData")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ConvertedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PostProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PostProductId");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_ClickEvents_SessionId");

                    b.HasIndex("UserId");

                    b.HasIndex("PostId", "CreatedAt")
                        .HasDatabaseName("IX_ClickEvents_PostId_CreatedAt");

                    b.ToTable("ClickEvents");
                });

            modelBuilder.Entity("Lyke.Core.Entities.ContentReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalDetails")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ReportedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PostId")
                        .HasDatabaseName("IX_ContentReports_PostId");

                    b.HasIndex("ReportedByUserId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("PostId", "ReportedByUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_ContentReports_PostId_ReportedByUserId");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_ContentReports_Status_CreatedAt");

                    b.ToTable("ContentReports");
                });

            modelBuilder.Entity("Lyke.Core.Entities.Creator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("PayoutDetails")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SocialLinks")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VerificationDocumentUrls")
                        .HasColumnType("jsonb");

                    b.Property<string>("VerificationNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("VerificationRejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("VerificationRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VerificationReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VerificationReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("VerificationStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("VerificationReviewedByUserId");

                    b.HasIndex("VerificationStatus");

                    b.ToTable("Creators");
                });

            modelBuilder.Entity("Lyke.Core.Entities.CreatorEarning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("ClickEventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("EarningType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ClickEventId")
                        .IsUnique();

                    b.HasIndex("CreatorId", "Status")
                        .HasDatabaseName("IX_CreatorEarnings_CreatorId_Status");

                    b.ToTable("CreatorEarnings");
                });

            modelBuilder.Entity("Lyke.Core.Entities.DailyMetricSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Clicks")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Conversions")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("Earnings")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("FiltersApplied")
                        .HasColumnType("integer");

                    b.Property<long>("Likes")
                        .HasColumnType("bigint");

                    b.Property<int>("NewUsers")
                        .HasColumnType("integer");

                    b.Property<int>("PostsPublished")
                        .HasColumnType("integer");

                    b.Property<decimal>("Revenue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<long>("Saves")
                        .HasColumnType("bigint");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ScopeEntityId")
                        .HasColumnType("uuid");

                    b.Property<int>("SearchesExecuted")
                        .HasColumnType("integer");

                    b.Property<long>("Shares")
                        .HasColumnType("bigint");

                    b.Property<long>("Views")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Date", "Scope")
                        .IsUnique()
                        .HasDatabaseName("IX_DailyMetricSnapshots_Date_Scope");

                    b.ToTable("DailyMetricSnapshots");
                });

            modelBuilder.Entity("Lyke.Core.Entities.Engagement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PostId", "CreatedAt")
                        .HasDatabaseName("IX_Engagements_PostId_CreatedAt");

                    b.HasIndex("UserId", "PostId", "Type")
                        .HasDatabaseName("IX_Engagements_UserId_PostId_Type");

                    b.ToTable("Engagements");
                });

            modelBuilder.Entity("Lyke.Core.Entities.FitTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("FitTags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "General",
                            IsActive = true,
                            Name = "True to size"
                        },
                        new
                        {
                            Id = 2,
                            Category = "General",
                            IsActive = true,
                            Name = "Runs small"
                        },
                        new
                        {
                            Id = 3,
                            Category = "General",
                            IsActive = true,
                            Name = "Runs large"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Fit",
                            IsActive = true,
                            Name = "Tight on hips"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Fit",
                            IsActive = true,
                            Name = "Tight on bust"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Fit",
                            IsActive = true,
                            Name = "Loose on waist"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Length",
                            IsActive = true,
                            Name = "Long in arms"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Length",
                            IsActive = true,
                            Name = "Short in arms"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Length",
                            IsActive = true,
                            Name = "Long in torso"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Length",
                            IsActive = true,
                            Name = "Short in torso"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Material",
                            IsActive = true,
                            Name = "Stretchy material"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Material",
                            IsActive = true,
                            Name = "Not stretchy"
                        });
                });

            modelBuilder.Entity("Lyke.Core.Entities.FrameSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("FrameSizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Shorter stature with a smaller overall frame",
                            DisplayOrder = 1,
                            Name = "Petite"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Medium height and proportional build",
                            DisplayOrder = 2,
                            Name = "Average"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Taller stature with a longer frame",
                            DisplayOrder = 3,
                            Name = "Tall"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Fuller figure across all areas",
                            DisplayOrder = 4,
                            Name = "Plus"
                        });
                });

            modelBuilder.Entity("Lyke.Core.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("MediaUrls")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ModeratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModeratedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModerationNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ThumbnailUrls")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ModeratedByUserId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Posts_Status");

                    b.HasIndex("Status", "PublishedAt")
                        .HasDatabaseName("IX_Posts_Status_PublishedAt");

                    b.HasIndex("CreatorId", "Status", "PublishedAt")
                        .HasDatabaseName("IX_Posts_CreatorId_Status_PublishedAt");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Lyke.Core.Entities.PostFitTag", b =>
                {
                    b.Property<Guid>("PostProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("FitTagId")
                        .HasColumnType("integer");

                    b.HasKey("PostProductId", "FitTagId");

                    b.HasIndex("FitTagId");

                    b.ToTable("PostFitTags");
                });

            modelBuilder.Entity("Lyke.Core.Entities.PostProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FitNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FitRating")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("SizeWorn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StylingNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PostId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("IX_PostProducts_PostId_ProductId");

                    b.ToTable("PostProducts");
                });

            modelBuilder.Entity("Lyke.Core.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ExternalSku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrls")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("ProductUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("RetailerId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RetailerId", "ExternalSku")
                        .IsUnique()
                        .HasDatabaseName("IX_Products_RetailerId_ExternalSku");

                    b.HasIndex("RetailerId", "Category", "IsActive")
                        .HasDatabaseName("IX_Products_RetailerId_Category_IsActive");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Lyke.Core.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshTokens_Token");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("IX_RefreshTokens_UserId_ExpiresAt");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Lyke.Core.Entities.Retailer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AffiliateConfig")
                        .HasColumnType("jsonb");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Retailers_UserId");

                    b.ToTable("Retailers");
                });

            modelBuilder.Entity("Lyke.Core.Entities.SponsoredPlacement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BudgetAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RetailerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SpentAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TargetBodyTypes")
                        .HasColumnType("jsonb");

                    b.Property<string>("TargetCategories")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("RetailerId");

                    b.HasIndex("IsActive", "StartDate", "EndDate")
                        .HasDatabaseName("IX_SponsoredPlacements_IsActive_Dates");

                    b.ToTable("SponsoredPlacements");
                });

            modelBuilder.Entity("Lyke.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MarketingOptIn")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PrivacyPolicyAcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PrivacyPolicyVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SuspendedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SuspendedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Users_IsActive");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Lyke.Core.Entities.UserFollow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("FollowedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FollowerUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FollowedUserId");

                    b.HasIndex("FollowerUserId", "FollowedUserId")
                        .IsUnique();

                    b.ToTable("UserFollows");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Lyke.Core.Entities.BodyProfile", b =>
                {
                    b.HasOne("Lyke.Core.Entities.BodyType", "BodyType")
                        .WithMany("BodyProfiles")
                        .HasForeignKey("BodyTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lyke.Core.Entities.FrameSize", "FrameSize")
                        .WithMany("BodyProfiles")
                        .HasForeignKey("FrameSizeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lyke.Core.Entities.User", "User")
                        .WithOne("BodyProfile")
                        .HasForeignKey("Lyke.Core.Entities.BodyProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BodyType");

                    b.Navigation("FrameSize");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lyke.Core.Entities.BodyProfileFitPreference", b =>
                {
                    b.HasOne("Lyke.Core.Entities.BodyProfile", "BodyProfile")
                        .WithMany("FitPreferences")
                        .HasForeignKey("BodyProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BodyProfile");
                });

            modelBuilder.Entity("Lyke.Core.Entities.ClickEvent", b =>
                {
                    b.HasOne("Lyke.Core.Entities.Post", "Post")
                        .WithMany("ClickEvents")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lyke.Core.Entities.PostProduct", "PostProduct")
                        .WithMany("ClickEvents")
                        .HasForeignKey("PostProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lyke.Core.Entities.User", "User")
                        .WithMany("ClickEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Post");

                    b.Navigation("PostProduct");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lyke.Core.Entities.ContentReport", b =>
                {
                    b.HasOne("Lyke.Core.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lyke.Core.Entities.User", "ReportedByUser")
                        .WithMany()
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lyke.Core.Entities.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Post");

                    b.Navigation("ReportedByUser");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("Lyke.Core.Entities.Creator", b =>
                {
                    b.HasOne("Lyke.Core.Entities.User", "User")
                        .WithOne("Creator")
                        .HasForeignKey("Lyke.Core.Entities.Creator", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lyke.Core.Entities.User", "VerificationReviewedByUser")
                        .WithMany()
                        .HasForeignKey("VerificationReviewedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");

                    b.Navigation("VerificationReviewedByUser");
                });

            modelBuilder.Entity("Lyke.Core.Entities.CreatorEarning", b =>
                {
                    b.HasOne("Lyke.Core.Entities.ClickEvent", "ClickEvent")
                        .WithOne("Earning")
                        .HasForeignKey("Lyke.Core.Entities.CreatorEarning", "ClickEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lyke.Core.Entities.Creator", "Creator")
                        .WithMany("Earnings")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClickEvent");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Lyke.Core.Entities.Engagement", b =>
                {
                    b.HasOne("Lyke.Core.Entities.Post", "Post")
                        .WithMany("Engagements")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lyke.Core.Entities.User", "User")
                        .WithMany("Engagements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lyke.Core.Entities.Post", b =>
                {
                    b.HasOne("Lyke.Core.Entities.Creator", "Creator")
                        .WithMany("Posts")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lyke.Core.Entities.User", "ModeratedByUser")
                        .WithMany()
                        .HasForeignKey("ModeratedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Creator");

                    b.Navigation("ModeratedByUser");
                });

            modelBuilder.Entity("Lyke.Core.Entities.PostFitTag", b =>
                {
                    b.HasOne("Lyke.Core.Entities.FitTag", "FitTag")
                        .WithMany("PostFitTags")
                        .HasForeignKey("FitTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lyke.Core.Entities.PostProduct", "PostProduct")
                        .WithMany("FitTags")
                        .HasForeignKey("PostProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FitTag");

                    b.Navigation("PostProduct");
                });

            modelBuilder.Entity("Lyke.Core.Entities.PostProduct", b =>
                {
                    b.HasOne("Lyke.Core.Entities.Post", "Post")
                        .WithMany("PostProducts")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lyke.Core.Entities.Product", "Product")
                        .WithMany("PostProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Lyke.Core.Entities.Product", b =>
                {
                    b.HasOne("Lyke.Core.Entities.Retailer", "Retailer")
                        .WithMany("Products")
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Retailer");
                });

            modelBuilder.Entity("Lyke.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("Lyke.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lyke.Core.Entities.Retailer", b =>
                {
                    b.HasOne("Lyke.Core.Entities.User", "User")
                        .WithOne("Retailer")
                        .HasForeignKey("Lyke.Core.Entities.Retailer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lyke.Core.Entities.SponsoredPlacement", b =>
                {
                    b.HasOne("Lyke.Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Lyke.Core.Entities.Retailer", "Retailer")
                        .WithMany("SponsoredPlacements")
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Retailer");
                });

            modelBuilder.Entity("Lyke.Core.Entities.UserFollow", b =>
                {
                    b.HasOne("Lyke.Core.Entities.User", "Followed")
                        .WithMany("Followers")
                        .HasForeignKey("FollowedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lyke.Core.Entities.User", "Follower")
                        .WithMany("Following")
                        .HasForeignKey("FollowerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Followed");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Lyke.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Lyke.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lyke.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Lyke.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lyke.Core.Entities.BodyProfile", b =>
                {
                    b.Navigation("FitPreferences");
                });

            modelBuilder.Entity("Lyke.Core.Entities.BodyType", b =>
                {
                    b.Navigation("BodyProfiles");
                });

            modelBuilder.Entity("Lyke.Core.Entities.ClickEvent", b =>
                {
                    b.Navigation("Earning");
                });

            modelBuilder.Entity("Lyke.Core.Entities.Creator", b =>
                {
                    b.Navigation("Earnings");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Lyke.Core.Entities.FitTag", b =>
                {
                    b.Navigation("PostFitTags");
                });

            modelBuilder.Entity("Lyke.Core.Entities.FrameSize", b =>
                {
                    b.Navigation("BodyProfiles");
                });

            modelBuilder.Entity("Lyke.Core.Entities.Post", b =>
                {
                    b.Navigation("ClickEvents");

                    b.Navigation("Engagements");

                    b.Navigation("PostProducts");
                });

            modelBuilder.Entity("Lyke.Core.Entities.PostProduct", b =>
                {
                    b.Navigation("ClickEvents");

                    b.Navigation("FitTags");
                });

            modelBuilder.Entity("Lyke.Core.Entities.Product", b =>
                {
                    b.Navigation("PostProducts");
                });

            modelBuilder.Entity("Lyke.Core.Entities.Retailer", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SponsoredPlacements");
                });

            modelBuilder.Entity("Lyke.Core.Entities.User", b =>
                {
                    b.Navigation("BodyProfile");

                    b.Navigation("ClickEvents");

                    b.Navigation("Creator");

                    b.Navigation("Engagements");

                    b.Navigation("Followers");

                    b.Navigation("Following");

                    b.Navigation("Retailer");
                });
#pragma warning restore 612, 618
        }
    }
}
